SELECT 
 -- A.REPORT_DAY
 -- ,SPN.pc_Nut1
--  ,SPN.nut1_name
  CASE WHEN (VIEWING.PROFILE_ID is not null) THEN 'YES' ELSE 'NO' END VIEWPROFILE
  ,COUNT(DISTINCT A.PROFILE_ID) AS ACTIVE_BASE
FROM (SELECT
  REPORT_DAY
  ,PROFILE_ID
FROM `sdp-sandbox-nowtv-prod.SDP_NOWTV_DI_VIEWS.BFTM3_ALL_LEVELS_STAGE4`
WHERE REPORT_DAY = '2025-05-17'
  AND REPORTING_PRODUCT_TYPE = 'PRODUCT'
  AND PRODUCT = 'SPORTS'
  AND CUST_PRODUCT_STATUS in ('Active', 'Pending Cancellation')
 AND ACCOUNT_TYPE = 'PS'
  AND COUNTRY_CODE = 'UK'
GROUP BY ALL) A INNER JOIN `sdp-sandbox-nowtv-int.JWN43.Nuts_Sports_Custs` SPN
ON SPN.PROFILE_ID = A.PROFILE_ID AND A.REPORT_DAY BETWEEN DATE(SPN.EFFECTIVE_FROM) AND DATE(SPN.EFFECTIVE_TO)
LEFT JOIN (SELECT
        V.profile_ID
        ,V.VIEWING_DATE      
FROM `sdp-sandbox-nowtv-prod.DATAMARTS.VADES` V 
WHERE COUNTRY_CODE = 'UK'
  AND VIEWING_DATE ='2025-05-17'
  AND PRODUCT = "SPORTS"
  AND VIEWING_SCENARIO = 'LIVE') VIEWING ON  VIEWING.PROFILE_id = a.PROFILE_ID  AND VIEWING.VIEWING_DATE = REPORT_DAY
GROUP BY ALL
ORDER BY 1

